spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.146:8848

server:
  port: 10201

dubbo:
  application:
    name: consumer
    qos-enable: false
  registry:
    address: nacos://192.168.10.146:8848
  scan:
    basePackages: com.funtl.alibaba.dubbo.consumer.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
